[package]
name = "Project-Rusted-Gold"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
untrusted = "0.7.1"
ring = "0.16.20"
